language: python
dist: bionic
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
 matrix:
   - TF_VER = 1.11
   - TF_VER = 1.10
install:
 - pip install -r requirements.txt
script:
 - bash test_travis/train_task.sh